version: "3.8"
services:
  greffer:
    build: .
    image: &app app
    restart: unless-stopped
    networks:
      - internal
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - env.env
    extra_hosts:
      - "greffon.io:host-gateway"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    build: ./nginx
    restart: unless-stopped
    networks:
      - internal
    extra_hosts:
      - myhost:host-gateway
    ports:
      - 8001:443
networks:
  internal: {}